### ISSUE TITLE
jms-client Sink.java don't allow asynchronous listener

### ISSUE THREAD

**Issue by klem14** [NordicWayInterchange/interchange#306]
The way _sink.java_ file from _jms-client_ module is built, doesn't allow the setup of a asynchronous message receiver.

The start() function indeed calls the start of the connection (in the _createConsumer_ function) before setting up the listener (SetMessageListener). Hence no listener is "associated" to the connection.

The synchrounous reception of the message doesn't suffer this limitation by calling the _createConsumer_ directly (as done in _SourceSinkIT.jav_a).

I have fixed the issue, and will be pleased to share this piece of code with you. Let me know.

Best regards.

Clement

**Comment by kyrrek** [comment]
This has been changed so that an implementor can make both an asynchronous MessageListener and ExceptionListener
