### ISSUE TITLE
Cause: General SSLEngine problem

### ISSUE THREAD

**Issue by tuomas81** [NordicWayInterchange/interchange#84]
I am seeing this from logs:

ful             - Could not refresh JMS Connection for destination 'onramp' - retrying using FixedBackOff{interval=5000, currentAttempts=449, maxAttempts=unlimited}. Cause: General SSLEngine problem
local_interchange_app          |  2019-11-28 09:57:48  [rContainer-1]  ERROR  o.a.qpid.jms.JmsConnection      connect                                      - Failed to connect to remote at: amqps://tieto.itsinterchange.eu:-1
local_interchange_app          |  2019-11-28 09:57:48  [rContainer-1]  ERROR  efaultMessageListenerContainer  refreshConnectionUntilSuccessful             - Could not refresh JMS Connection for destination 'onramp' - retrying using FixedBackOff{interval=5000, currentAttempts=450, maxAttempts=unlimited}. Cause: General SSLEngine problem
local_interchange_app          |  2019-11-28 09:57:53  [rContainer-1]  ERROR  o.a.qpid.jms.JmsConnection      connect                                      - Failed to connect to remote at: amqps://tieto.itsinterchange.eu:-1
local_interchange_app          |  2019-11-28 09:57:53  [rContainer-1]  ERROR  efaultMessageListenerContainer  refreshConnectionUntilSuccessful             - Could not refresh JMS Connection for destination 'onramp' - retrying using FixedBackOff{interval=5000, currentAttempts=451, maxAttempts=unlimited}. Cause: General SSLEngine problem
local_interchange_app          |  2019-11-28 09:57:58  [rContainer-1]  ERROR  o.a.qpid.jms.JmsConnection      connect                                      - Failed to connect to remote at: amqps://tieto.itsinterchange.eu:-1
local_interchange_app          |  2019-11-28 09:57:58  [rContainer-1]  ERROR  efaultMessageListenerContainer  refreshConnectionUntilSuccessful             - Could not refresh JMS Connection for destination 'onramp' - retrying using FixedBackOff{interval=5000, currentAttempts=452, maxAttempts=unlimited}. Cause: General SSLEngine problem

Running client testing toward node and it stays in status:
Using url [amqps://tieto.itsinterchange.eu:5671] sendQueue [onramp] outQueue [eee]
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Connecting to: amqps://tieto.itsinterchange.eu:5671
 rece queue: eee
 send queue: onramp
 Waiting for messages..

Assuming that it is seen on abowe node logs.
I am missing something from setup?

**Comment by RogerMartinsen** [comment]
The interchange_app is supposed to use amqp (not amqps) to connect to the message broker.

**Comment by tuomas81** [comment]
> The interchange_app is supposed to use amqp (not amqps) to connect to the message broker.

So need to change preferences? amqps -> amqp

I will make a change and test

**Comment by tuomas81** [comment]
with that change when running client test ti will give this error:

[root@nw2ic01 interchange-federation-master]# ./eee_test-client.sh
Using url [amqp://tieto.itsinterchange.eu:5671] sendQueue [onramp] outQueue [eee]
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Connecting to: amqp://tieto.itsinterchange.eu:5671
 rece queue: eee
 send queue: onramp
org.apache.qpid.jms.exceptions.JMSSecuritySaslException: Could not find a suitable SASL mechanism. No supported mechanism, or none usable with the available credentials. Server offered: [EXTERNAL]

**Comment by tuomas81** [comment]
My test client conf is like this:


#!/bin/bash -eu

if [[ ! -d ./debugclient/target ]]; then
    echo "ERROR - debug client not found. Have you built it?"
    exit 1
fi

SERVER=${1:-tieto.itsinterchange.eu}

KEYSTORE_FILE="./tmp/keys/chain.tieto.itsinterchange.eu.p12"
TRUSTSTORE_FILE="./tmp/keys/truststore.jks"
PASSWORD=xxxxxxx
PASSWORD2=yyyyyyy
CLIENT_JAR=debugclient/target/debugclient-1.0-SNAPSHOT-jar-with-dependencies.jar
SERVER_URI="amqp://${SERVER}:5671"
SEND_QUEUE=onramp
RECEIVE_QUEUE=eee

java \
    -Djavax.net.ssl.keyStore=${KEYSTORE_FILE} \
    -Djavax.net.ssl.keyStorePassword=${PASSWORD} \
    -Djavax.net.ssl.keyStoreType=pkcs12 \
    -Djavax.net.ssl.trustStore=${TRUSTSTORE_FILE} \
    -Djavax.net.ssl.trustStorePassword=${PASSWORD2} \
    -jar ${CLIENT_JAR} \
    ${SERVER_URI} ${SEND_QUEUE} ${RECEIVE_QUEUE}

In example client test this row SERVER_URI="amqp://${SERVER}:5671" wasSERVER_URI="amqps://${SERVER}:5671"

Should it be like that or is there other issues?

**Comment by kyrrek** [comment]
The SERVER_URI should be amqps://... . We always use SSL

**Comment by tuomas81** [comment]
Ok, tested with that one:

[root@nw2ic01 interchange-federation-master]# ./eee_test-client.sh
Using url [amqps://tieto.itsinterchange.eu:5671] sendQueue [onramp] outQueue [eee]
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Connecting to: amqps://tieto.itsinterchange.eu:5671
 rece queue: eee
 send queue: onramp

Log also looks good now

**Comment by RogerMartinsen** [comment]
The only place we use amqp is the connection from interchange_app to the broker. This traffic is supposed to be held internally on the cluster.

All other messaging clients use amqps.
