### ISSUE TITLE
database content after restart of node

### ISSUE THREAD

**Issue by tuomas81** [NordicWayInterchange/interchange#86]
When node is restarted i noticed that content of database is lost.

This means that all subscriptions are lost node self presentation is lost and client need to do all of those actions again.

This issue would cause problems of following scenario's:

1. Server have maintenance break and node need to be stopped
2. Node crashes and is restarted
3. Setting's in node are change that requires restart for node.

Proposal how to fix this:
Could that container database that is build when node is started be local database? 

Pros:
When node need to be stopped and database is local database it would keep all of those information's saved and this would make updating, maintenance work and restoring service after critical incident more  robust and time would be saved on recovery work.
It's also would mean that client do not need to do any extra steps when this kind of activity is performed.

Cons:
Small amount of space is needed for standalone db
Separate installation is needed for db

**Comment by kyrrek** [comment]
Sorry for the late reply. It's possible to make the data persist between restarts, you only have to mount the database dir to a persistent volume.
This is described in "Where to Store Data" in the description of the postgres Docker image: https://hub.docker.com/_/postgres.
The link describes how to do this in plain Docker, there are similar constructs for Docker Compose or Kubernetes.

**Comment by kyrrek** [comment]
Closing this issue. If there are more questions regarding persistence of database data, please reopen.
